---
final_name: crate
blobstore:
  provider: s3
  options:
    bucket_name: crate-boshrelease
    access_key_id: AKIAJPWUHOHV42IMTNQQ
    secret_access_key: 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
    encryption_key: cloudfoundry-community
