<%
director_uuid = 'CHANGE-ME'
deployment_name = 'crate'
%>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: crate
   version: latest

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: 32
  serial: false

networks:
  - name: default
    subnets:
      # network with static ip used for web
      - range: 10.244.8.0/30
        reserved: [10.244.8.1]
        static: [10.244.8.2]
        cloud_properties: {}
      # networks for dynamic ips (db, workers, compilation vms)
      - range: 10.244.8.4/30
        reserved: [10.244.8.5]
        static: [10.244.8.6]
        cloud_properties: {}
      - range: 10.244.8.8/30
        reserved: [10.244.8.9]
        static: [10.244.8.10]
        cloud_properties: {}
      - range: 10.244.8.12/30
        reserved: [10.244.8.13]
        cloud_properties: {}
      - range: 10.244.8.16/30
        reserved: [10.244.8.17]
        cloud_properties: {}
      - range: 10.244.8.20/30
        reserved: [10.244.8.21]
        cloud_properties: {}

resource_pools:
  - name: default
    network: default
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties: {}

jobs:
  - name: crate
    templates:
      - name: crate
    instances: 3
    resource_pool: default
    persistent_disk: 16384
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.244.8.2
          - 10.244.8.6
          - 10.244.8.10

properties:
  crate:
    master_nodes:
      - 10.244.8.2
      - 10.244.8.6
      - 10.244.8.10
